### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by beta442** [KREeDo5/Study-OP#1]
https://github.com/KREeDo5/Study-OP/blob/90e7bfa94b244e8eb7eade2ed457d1583d83594d/LW_2/231.pas#L1-L17
- [ ] Исправить ошибку форматирования

**Comment by KREeDo5** [comment]
https://github.com/KREeDo5/Study-OP/blob/90e7bfa94b244e8eb7eade2ed457d1583d83594d/LW_2/231.pas#L1-L17
- [ ] Исправить ошибку форматирования
